In [6]:
# Predicting whether the customer is going to buy the product or not
# so it comes under supervised learning.

In [7]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv('Book1.csv')

In [9]:
df.head()

AGE     SAL  YES/NO
0   63  119198       0
1   38  152298       0
2   23   38670       0
3   30   40127       0
4   21  146963       1

In [10]:
df.shape

(399, 3)

In [11]:
# segregate dataset into X(input) and Y(output)

In [19]:
x=df.iloc[:,:-1].values
x

array([[    63, 119198],
       [    38, 152298],
       [    23,  38670],
       [    30,  40127],
       [    21, 146963],
       [    37,  56431],
       [    34, 171446],
       [    67, 155181],
       [    53, 161950],
       [    46,  93442],
       [    22,  66000],
       [    24, 177033],
       [    23,  84100],
       [    41,  79290],
       [    18, 143700],
       [    63, 145506],
       [    22, 150277],
       [    65,  25684],
       [    23,  35205],
       [    67,  47155],
       [    69,  73930],
       [    37,  35900],
       [    57,  47616],
       [    40, 177919],
       [    53, 155592],
       [    67, 144884],
       [    58,  44927],
       [    48, 149468],
       [    39, 109907],
       [    19, 176178],
       [    49, 129036],
       [    23, 131050],
       [    33, 150617],
       [    45,  89326],
       [    57,  80887],
       [    51, 108290],
       [    66, 164118],
       [    21,  45241],
       [    54,  92875],
       [    49,  51866],


In [22]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,

In [23]:
#splitting dataset into train and test

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [25]:
# future Scaling

In [26]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test= sc.transform(x_test)
print(x_train)

[[ 1.67413886e+00  1.68280763e+00]
 [ 7.75684340e-01  5.02173773e-01]
 [ 7.11509017e-01  1.00474566e+00]
 [-1.40627665e+00  1.16692657e+00]
 [-5.07822122e-01 -4.54861791e-01]
 [ 8.39859664e-01 -8.44689807e-01]
 [ 8.39859664e-01  1.56595266e+00]
 [-3.79471476e-01 -5.60691533e-01]
 [-2.51120830e-01 -4.31960044e-01]
 [ 1.60996354e+00 -1.08915506e+00]
 [ 7.75684340e-01  1.26264466e+00]
 [ 1.03238563e+00  6.53495561e-01]
 [-3.15296153e-01 -7.75652355e-01]
 [-3.79471476e-01 -1.28856428e+00]
 [ 9.68210310e-01  1.59358840e+00]
 [-1.21375068e+00 -1.43290063e-01]
 [-2.51120830e-01  5.54559184e-01]
 [-1.02122471e+00 -7.40865063e-02]
 [ 1.33931109e-01  6.46062356e-01]
 [ 1.35326225e+00 -1.17729460e+00]
 [ 1.98106432e-01 -4.16387687e-01]
 [ 1.73831419e+00  8.89094948e-01]
 [-1.27792600e+00  3.36326812e-02]
 [ 6.47333694e-01  1.68916115e+00]
 [ 6.47333694e-01  1.56784210e+00]
 [ 4.54807725e-01  1.04895039e+00]
 [ 9.04034987e-01 -1.04530330e+00]
 [ 1.41743757e+00  4.80912314e-01]
 [ 5.18983048e-01 -9

In [27]:
#training

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [33]:
# prediction of data

In [32]:
y_pred=model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]]


In [34]:
# the first column is predicted value and second one is tested value

In [35]:
# Confusion Matrix

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test,y_pred)
print('Confusion Matrix: ')
print(cm)
print("Accuracy of the model: {0}%".format(accuracy_score(y_test,y_pred)*100))

Confusion Matrix: 
[[23 19]
 [26 32]]
Accuracy of the model: 55.00000000000001%


In [37]:
# prediction

In [39]:
age = int(input("Enter New Customers Age:"))
sal=int(input("enter new customers salary"))
newcust=[[age,sal]]
result=model.predict(sc.transform(newcust))
print(result)
if result == 1:
    print('customer will buy')
else:
    print('customer will not buy')

Enter New Customers Age:45
enter new customers salary50000
[0]
customer will not buy
